#!/bin/bash

# Make Windows Edge the default browser inside WSL so `open`/xdg-open and
# $BROWSER all route to it instead of a Linux-side browser.
#
# Note: xdg-open consults the xdg-mime default handler BEFORE $BROWSER, so
# setting $BROWSER alone is not enough — this also registers a desktop entry.
# ($BROWSER itself is exported in .bashrc, which sources from this repo.)
#
# Idempotent; safe to re-run. Needs sudo only if /usr/local/bin/edge-wsl
# is missing or out of date.

set -euo pipefail

if ! grep -qi microsoft /proc/version 2>/dev/null; then
  echo "Not running under WSL; skipping browser setup."
  exit 0
fi

# --- Locate the Windows Edge executable ---------------------------------
EDGE_EXE=""
for candidate in \
  "/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" \
  "/mnt/c/Program Files/Microsoft/Edge/Application/msedge.exe"; do
  if [ -x "$candidate" ]; then
    EDGE_EXE="$candidate"
    break
  fi
done

if [ -z "$EDGE_EXE" ]; then
  echo "ERROR: msedge.exe not found under /mnt/c — is the C: drive mounted?" >&2
  exit 1
fi

# --- Wrapper: translate Linux paths to Windows paths, then launch Edge ---
WRAPPER=/usr/local/bin/edge-wsl
WRAPPER_CONTENT="#!/bin/bash
# Open a URL or file in Windows Edge from WSL (generated by dotfiles/setup-wsl-browser.sh).
args=()
for arg in \"\$@\"; do
  if [[ -e \"\$arg\" ]]; then
    args+=(\"\$(wslpath -w \"\$arg\")\")
  elif [[ \"\$arg\" == file://* ]]; then
    args+=(\"\$(wslpath -w \"\${arg#file://}\")\")
  else
    args+=(\"\$arg\")
  fi
done
exec \"$EDGE_EXE\" \"\${args[@]}\"
"

# Compare contents, not just existence — an out-of-date wrapper needs replacing,
# and existence-only checks let a stale version linger forever.
if printf '%s' "$WRAPPER_CONTENT" | diff -q - "$WRAPPER" > /dev/null 2>&1; then
  echo "$WRAPPER is up to date."
else
  if [ -e "$WRAPPER" ]; then
    echo "Updating $WRAPPER (requires sudo)..."
  else
    echo "Installing $WRAPPER (requires sudo)..."
  fi
  printf '%s' "$WRAPPER_CONTENT" | sudo tee "$WRAPPER" > /dev/null
  sudo chmod +x "$WRAPPER"
fi

# --- Desktop entry so xdg-open resolves to the wrapper -------------------
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/msedge-windows.desktop"
mkdir -p "$DESKTOP_DIR"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Version=1.0
Name=Microsoft Edge (Windows)
Comment=Open in the Windows-side Edge browser
Exec=$WRAPPER %u
Type=Application
Terminal=false
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/pdf;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/about;x-scheme-handler/unknown;
EOF

command -v update-desktop-database > /dev/null && update-desktop-database "$DESKTOP_DIR"

# --- Register as default browser and text/html handler -------------------
# env -u BROWSER: xdg-settings refuses to run while $BROWSER is set.
env -u BROWSER xdg-settings set default-web-browser msedge-windows.desktop
xdg-mime default msedge-windows.desktop \
  text/html application/xhtml+xml \
  x-scheme-handler/http x-scheme-handler/https

echo "Done. Default browser: $(env -u BROWSER xdg-settings get default-web-browser)"
echo "text/html handler:     $(xdg-mime query default text/html)"
